<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Telegram Bot Credentials (for Mini App HMAC authentication & Bot API)
    |--------------------------------------------------------------------------
    */
    'bot_token' => env('TELEGRAM_BOT_TOKEN'),
    'bot_username' => env('TELEGRAM_BOT_USERNAME'),
    'webhook_secret' => env('TELEGRAM_WEBHOOK_SECRET'),

    /*
    |--------------------------------------------------------------------------
    | Default MTProto Client Settings (from https://my.telegram.org)
    |--------------------------------------------------------------------------
    */
    'api_id' => env('TELEGRAM_API_ID'),
    'api_hash' => env('TELEGRAM_API_HASH'),
    'dc_id' => (int)env('TELEGRAM_DC_ID', 2),

    /*
    |--------------------------------------------------------------------------
    | Default Saved MTProto Sessions (Generated by `php artisan teleproto:login`)
    |--------------------------------------------------------------------------
    */
    'user_session' => env('TELEGRAM_USER_SESSION'),
    'bot_session' => env('TELEGRAM_BOT_SESSION'),

    /*
    |--------------------------------------------------------------------------
    | Redis Streams & Command Queues
    |--------------------------------------------------------------------------
    */
    'redis_connection' => env('TELEGRAM_REDIS_CONNECTION', 'default'),
    'update_stream' => env('TELEGRAM_UPDATE_STREAM', 'tg:stream:updates'),
    'command_queue_prefix' => env('TELEGRAM_COMMAND_QUEUE_PREFIX', 'tg:queue:commands:'),
];

