<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Telegram Bot Credentials (for Mini App HMAC authentication & Bot API)
    |--------------------------------------------------------------------------
    */
    'bot_token' => env('TELEGRAM_BOT_TOKEN'),
    'webhook_secret' => env('TELEGRAM_WEBHOOK_SECRET'),

    /*
    |--------------------------------------------------------------------------
    | Default MTProto Client Settings (from https://my.telegram.org)
    |--------------------------------------------------------------------------
    */
    'api_id' => env('TELEGRAM_API_ID'),
    'api_hash' => env('TELEGRAM_API_HASH'),
    'dc_id' => (int)env('TELEGRAM_DC_ID', 2),
    'live_mode' => env('TELEPROTO_LIVE', false),

    /*
    |--------------------------------------------------------------------------
    | Default Saved MTProto Sessions (Generated by `php artisan teleproto:login`)
    |--------------------------------------------------------------------------
    */
    'user_session' => env('TELEGRAM_USER_SESSION'),
    'bot_session' => env('TELEGRAM_BOT_SESSION'),
];

